hypertube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", include("tube.urls")),
    path('admin/', admin.site.urls, name="admin"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tube/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import IndexView
from .views import LoginView
from .views import LogoutView
from .views import RegisterView
from .views import UploadView
from .views import WatchView
from .views import VideoResponseView

app_name = "tube"
urlpatterns = [
    path("", RedirectView.as_view(url="tube/")),
    path("tube/", IndexView.as_view(), name="index"),
    path("tube/upload/", UploadView.as_view(), name="upload"),

    path("tube/<str:file_name>", VideoResponseView.as_view(), name="video"),
    path("tube/watch/<int:video_id>/", WatchView.as_view(), name="watch"),

    path("login", RedirectView.as_view(url="login/")),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", RegisterView.as_view(), name="register"),
]

tube/models/tag.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "tags"

    def __str__(self):
        return self.name

tube/models/video.py
from django.db import models


class Video(models.Model):
    file = models.FileField()
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

    @staticmethod
    def find_all():
        return Video.objects.all()

tube/models/video_tag.py
from django.db import models

from .tag import Tag
from .video import Video


class VideoTag(models.Model):
    tag = models.ForeignKey(Tag, related_name="tag", on_delete=models.CASCADE)
    video = models.ForeignKey(Video, related_name="video", on_delete=models.CASCADE)

tube/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UploadVideoForm(forms.Form):
    video = forms.FileField(label="Select a video:")
    title = forms.CharField(label="Title:")
    tags = forms.CharField(label="Point tags:")


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2")

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        if commit:
            user.save()
        return user

tube/views.py
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse
from django.http import HttpRequest
from django.shortcuts import redirect
from django.shortcuts import render
from django.views import View

from .forms import RegisterForm
from .forms import UploadVideoForm
from .models.tag import Tag
from .models.video import Video
from .models.video_tag import VideoTag


class IndexView(View):
    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        if tag := request.GET.get("tag", None):
            video_tags = VideoTag.objects.filter(tag__name__iexact=tag)
            videos = [video_tag.video for video_tag in video_tags]
        elif query := request.GET.get("q", None):
            video_tags = VideoTag.objects.filter(video__title__icontains=query)
            videos = [vt.video for vt in video_tags]
        else:
            videos = Video.find_all()

        context = {
            "videos": videos or None,
            "tag": tag or None,
            "title": "HyperTube | Home"
        }
        return render(request, "tube/index.html", context)


class LoginView(View):
    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        form = AuthenticationForm()
        return render(request, "tube/login.html", {"login_form": form})

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username", None)
            password = form.cleaned_data.get("password", None)
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("tube:index")
        messages.error(request, "Invalid credentials.")
        return redirect("tube:login")


class LogoutView(View):
    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect("tube:index")


class RegisterView(View):
    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        form = RegisterForm()
        return render(request, "tube/register.html", {"register_form": form})

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Successfully signed up.")
            return redirect("tube:login")
        messages.error(request, "Invalid credentials.")
        return redirect("tube:register")


class UploadView(View):
    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        form = UploadVideoForm()
        context = {
            "title": "HyperTube | Upload",
            "upload_form": form
        }
        return render(request, "tube/upload.html", context)

        # NOTE: will not pass test #13
        # if request.user.is_authenticated:
        #     context = {
        #         "title": "HyperTube | Upload",
        #         "upload_form": form
        #     }
        #     return render(request, "tube/upload.html", context)
        # return redirect("tube:login")

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        form = UploadVideoForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES.get("video", None)
            title = request.POST.get("title", None)
            tag_names = request.POST.get("tags", None).split(" ")

            tags = [Tag.objects.create(name=name) for name in tag_names]
            video = Video.objects.create(file=file, title=title)
            for tag in tags:
                VideoTag.objects.create(tag=tag, video=video)

            messages.info(request, "File uploaded.")
        else:
            messages.error(request, "Failed to upload file.")
        return redirect("tube:index")


class VideoResponseView(View):
    def get(self, request: HttpRequest, file_name: str, *args, **kwargs) -> HttpResponse:
        with open(os.path.join(settings.MEDIA_ROOT, file_name), "rb") as f:
            file = f.read()
        response = HttpResponse(file, content_type="video/mp4")
        response["Accept-Ranges"] = "bytes"
        return response

        # if video := Video.objects.filter(file=file_name).first():
        #     path = settings.MEDIA_ROOT + "/" + video.file.name
        #     response = HttpResponse(video.file, content_type="video/mp4")
        #     response["Accept-Ranges"] = "bytes"
        #
        #     return response


class WatchView(View):
    def get(self, request: HttpRequest, video_id: int, *args, **kwargs) -> HttpResponse:
        print(f"video id = {video_id}")
        video_tag = VideoTag.objects.filter(video__id=video_id).first()

        tags = video_tag.tag.name.split(" ")
        print(f"tags = {tags}")

        context = {
            "title": "HyperTube | Watch",
            "video_tag": video_tag,
            "tags": tags,
        }
        return render(request, "tube/watch.html", context)

tube/templates/tube/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if title %}{{ title }}{% else %}HyperTube{% endif %}</title>
</head>
<body>

{% include "tube/header.html" %}

{% include "tube/messages.html" %}

{#{% if messages %}#}
{#    <ul class="messages">#}
{#        {% for message in messages %}#}
{#            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>#}
{#                {{ message }}#}
{#            </li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#{% endif %}#}

{#{% if user.is_authenticated %}#}
{#    <h2>Welcome, {{ user.username }}</h2>#}
{#    <a href="{% url 'tube:logout' %}">Logout</a>#}
{#{% endif %}#}

<main>
    {% block app_content %}{% endblock %}
</main>

{% include "tube/footer.html" %}

</body>
</html>

tube/templates/tube/footer.html
<footer>
    <p>Made with &hearts; by Zane. Powered by Django.</p>
</footer>

tube/templates/tube/header.html
<header>
    <h2>
        <a href="{% url 'tube:index' %}" target="_blank">Hypertube</a>
        {#<a href="{% url 'tube:index' %}" target="_blank">HyperTube</a>#}

    </h2>

    {% if request.user.is_superuser or request.user == task.user %}
        <a href="{% url 'admin.index' %}">Admin</a>
    {% endif %}

    <a href="{% url 'tube:upload' %}">Upload</a>
    <a href="{% url 'tube:login' %}" target="_blank">Login</a>
    {% if user.is_authenticated %}
        <a href="{% url 'tube:logout' %}">Logout</a>
        <h2>Welcome, {{ user.username }}</h2>
    {% else %}
        <h2>Welcome, stranger!</h2>
    {% endif %}
</header>

tube/templates/tube/index.html
{% extends "tube/base.html" %}

{% block app_content %}
    {#<h2>Hypertube</h2>#}
    {#<a href="{% url 'tube:login' %}" target="_blank">Log in</a>#}
    {#<a href="{% url 'tube:register' %}" target="_blank">Sign up</a>#}
    {##}
    {#<br><br>#}

    <form action="{% url 'tube:index' %}" method="get">
        <label for="search" hidden aria-hidden="true">Search</label>
        <input id="search"
               name="q"
               placeholder="Search..."
               type="text">
        <button type="submit">Search</button>
    </form>

    {% if tag %}
        <br>
        <a href="/tube/?tag={{ tag }}">#{{ tag }}</a>
    {% endif %}

    <p>{{ videos | length }} videos</p>
    {% if videos %}
        <ul>
            {% for video in videos %}
                <li><a href="/tube/watch/{{ video.id }}/"
                       target="_blank">{{ video.title }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
    <br><br>
    {#<a href="{% url 'tube:upload' %}" target="_blank">Upload</a>#}
    {#<a href="{% url 'tube:upload' %}">Upload</a>#}
{% endblock %}

tube/templates/tube/login.html
{% extends "tube/base.html" %}

{% block app_content %}
    <h1>Log in</h1>
    <form action="" method="post">
        {% csrf_token %}
        <table>{{ login_form.as_p }}</table>
        <button type="submit">Log in</button>
    </form>
    <br><br>
    <a href="{% url 'tube:register' %}">Sign up</a>
{% endblock %}

tube/templates/tube/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
        {% endfor %}
    </ul>
{% endif %}

tube/templates/tube/register.html
{% extends "tube/base.html" %}

{% block app_content %}
    <h1>Sign Up</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ register_form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
    <br><br>
    <a href="{% url 'tube:login' %}">Login</a>
{% endblock %}

tube/templates/tube/upload.html
{% extends "tube/base.html" %}

{% block app_content %}
    <form action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ upload_form.as_p }}
        <button type="submit">Upload</button>
    </form>
{% endblock %}

tube/templates/tube/watch.html
{% extends "tube/base.html" %}

{% block app_content %}
    {% if video_tag %}
        <p>{{ video_tag.video.title }}</p>
        {% for tag in tags %}
            <a href="/tube/?tag={{ tag }}" target="_blank">#{{ tag }}</a>
        {% endfor %}
        <br><br>
        <video width="640" height="480" controls>
            <source src="/tube/{{ video_tag.video.file.name }}" type="video/mp4">
        </video>
    {% endif %}
{% endblock %}